---
title: "Case Study 09"
author: Bobby Decker
date: 11/1/2022
output: github_document
---
#install.packages("ggmap")
#install.packages("rnoaa")
#install.packages("spData")
```{r}
#load libraries and data
library(sf)
library(tidyverse)
library(ggmap)
library(rnoaa)
library(spData)
data(world)
data(us_states)

#load data from url
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.points.zip"
```
```{r}
#create storm data object
tdir=tempdir()
download.file(dataurl,destfile=file.path(tdir,"temp.zip"))
unzip(file.path(tdir,"temp.zip"),exdir = tdir) #unzip the compressed folder
storm_data <- read_sf(list.files(tdir,pattern=".shp",full.names = T))

#extract 1950-present storms
storm_1950<-filter(storm_data, SEASON > 1949) %>%
mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x)) %>%
mutate(decade=(floor(year/10)*10))

#create region object
region<-st_bbox(storm_1950)
```
```{r}
#plot
ggplot(world)+
geom_sf()+
facet_wrap(~decade)+
stat_bin2d(data=storms, aes(y=st_coordinates(storms)[,2], x=st_coordinates(storms)[,1]),bins=100)+
scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])
```
```{r}
#table
us_storms<-st_transform(us_states) %>%
select(state=NAME) %>%
storm_states <- st_join(storms, states, join = st_intersects,left = F)
group_by(state)
summarize(storms=length(unique(NAME)))
arrange(desc(storms))
slice(1:5)
```
