---
title: "Case Study 08"
author: "Bobby Decker"
date: "10/27/2022"
output: 
  html_document: default
  github_document: default
  powerpoint_presentation: default
  word_document: default
---

#install.packages("kableExtra")
#install.packages("magick")

```{r ,echo = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(magick)
mauna_mean <- read_table("ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt", skip=57, col_names=c("year", "mean", "unc"))
```

```{r}
ggplot(mauna_mean, aes(year, mean))+
  geom_line(color="red", size=1.75)+
  labs(
    title="Annual Mean Carbon Dioxide Concentration",
    subtitle = "1959 - Present",
  )+
  xlab("Year")+
  ylab("Mauna Loa Annual Mean CO_2 (ppm)")
```

```{r}
top5_table<-arrange(mauna_mean, desc(mean))[1:5, ]
knitr::kable(top5_table, caption = 'Top Five Annual Mean Carbon Dioxide Concentrations at Mona Loa',
col.names = c("year", "mean", "unc")) %>%
as_image(width = 10,file = "table.png")
```

#rmarkdown::render("C:/Users/astro/Desktop/GEO511 real/case_studies-rjdecker98/week_08/case_study_08.Rmd", output_format = "all") 
